### ISSUE TITLE
Kinsta

### ISSUE THREAD

**Issue by kevnk** [statamic/hosts#35]
Has anyone tried Kinsta? https://kinsta.com/docs/statamic-example-application/

**Comment by jasonvarga** [comment]
We have a link on our docs to explain how to deploy. People must have tried it with some success!

**Comment by kevnk** [comment]
Cool. Is it worth adding to the README list? or does it have to meet some criteria to be considered "good" hosting?

**Comment by jasonvarga** [comment]
That's fine. Feel free to PR if you want.
